import { supabase } from '@/lib/supabase'

const VAPID_PUBLIC_KEY = import.meta.env.VITE_VAPID_PUBLIC_KEY as string | undefined

export type PushSupportStatus =
  | 'ready' // Push API + service workers available, safe to request permission
  | 'unsupported' // this browser/OS has no Push API at all
  | 'needs-ios-install' // iOS Safari supports push, but only once added to the Home Screen

/** Detects whether this browser can receive Web Push at all, before we ever prompt for permission. */
export function getPushSupportStatus(): PushSupportStatus {
  if (typeof window === 'undefined') return 'unsupported'

  const hasApis = 'serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window
  if (!hasApis) {
    const isIOS = /iphone|ipad|ipod/i.test(navigator.userAgent)
    const isStandalone =
      window.matchMedia('(display-mode: standalone)').matches ||
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      (navigator as any).standalone === true
    if (isIOS && !isStandalone) return 'needs-ios-install'
    return 'unsupported'
  }
  return 'ready'
}

/** Current browser permission state — 'default' means the user hasn't been asked yet. */
export function getNotificationPermission(): NotificationPermission | 'unsupported' {
  if (typeof Notification === 'undefined') return 'unsupported'
  return Notification.permission
}

/** Converts a VAPID public key from base64url (as generated by `web-push`) to the raw bytes the Push API expects. */
export function urlBase64ToUint8Array(base64String: string): Uint8Array<ArrayBuffer> {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4)
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/')
  const rawData = atob(base64)
  const bytes = new Uint8Array(rawData.length)
  for (let i = 0; i < rawData.length; i++) {
    bytes[i] = rawData.charCodeAt(i)
  }
  return bytes
}

/**
 * Requests permission (if not already decided), subscribes this device to
 * push, and saves the subscription against the authenticated user. Safe to
 * call again on a device that's already subscribed (upserts by endpoint).
 */
export async function subscribeToPush(userId: string): Promise<NotificationPermission> {
  if (!VAPID_PUBLIC_KEY) {
    throw new Error('Push notifications are not configured (missing VITE_VAPID_PUBLIC_KEY).')
  }

  let permission = Notification.permission
  if (permission === 'default') {
    permission = await Notification.requestPermission()
  }
  if (permission !== 'granted') {
    return permission
  }

  const registration = await navigator.serviceWorker.ready
  let subscription = await registration.pushManager.getSubscription()
  if (!subscription) {
    subscription = await registration.pushManager.subscribe({
      userVisibleOnly: true,
      applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY),
    })
  }

  const json = subscription.toJSON()
  if (!json.keys?.p256dh || !json.keys?.auth) {
    throw new Error('Push subscription is missing encryption keys.')
  }

  const { error } = await supabase.from('push_subscriptions').upsert(
    {
      user_id: userId,
      endpoint: subscription.endpoint,
      p256dh: json.keys.p256dh,
      auth_key: json.keys.auth,
      user_agent: navigator.userAgent,
      updated_at: new Date().toISOString(),
    },
    { onConflict: 'user_id,endpoint' },
  )
  if (error) throw error

  return permission
}

/** Removes this device's push subscription both from the browser and from Supabase. */
export async function unsubscribeFromPush(userId: string): Promise<void> {
  if (!('serviceWorker' in navigator)) return

  const registration = await navigator.serviceWorker.getRegistration()
  const subscription = await registration?.pushManager.getSubscription()
  if (!subscription) return

  const endpoint = subscription.endpoint
  await subscription.unsubscribe()

  const { error } = await supabase
    .from('push_subscriptions')
    .delete()
    .eq('user_id', userId)
    .eq('endpoint', endpoint)
  if (error) throw error
}

/** The browser's own IANA timezone, e.g. "Asia/Kolkata" — used to schedule this user's 10 PM reminder. */
export function detectTimezone(): string {
  try {
    return Intl.DateTimeFormat().resolvedOptions().timeZone || 'Asia/Kolkata'
  } catch {
    return 'Asia/Kolkata'
  }
}
